=== ArseniyK/Caracal/units/schema/language.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Language File Specification
	Copyright (c) 2010. by RCF Group
	
	Author: MeanEYE.rcf
-->
<!ELEMENT document (language*)>

<!ELEMENT language (constant*)>
<!ATTLIST language name CDATA #IMPLIED>
<!ATTLIST language short CDATA #REQUIRED>
<!ATTLIST language default (yes|no) "no">
<!ATTLIST language rtl (yes|no) "no">

<!ELEMENT constant ANY>
<!ATTLIST constant name CDATA #REQUIRED>
<!ATTLIST constant value CDATA #IMPLIED>

=== ArseniyK/Caracal/modules/page_info/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_page_info">Page settings</constant>
		
		<constant name="title_page_info">Page Settings</constant>
		
		<constant name="message_saved">Page settings were saved!</constant>
		
		<constant name="label_description">Page description (between 70 and 160 characters):</constant>
		<constant name="label_analytics">Google analytics ID:</constant>
	</language>
	<language short="iw">
		<constant name="menu_page_info">Page settings</constant>

		<constant name="title_page_info">Page Settings</constant>

		<constant name="message_saved">Page settings were saved!</constant>
		
		<constant name="label_description">Page description (between 70 and 160 characters):</constant>
		<constant name="label_analytics">Google analytics ID:</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/links/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language name="English" short="en">
		<!-- Menu Items -->
		<constant name="menu_links">Links</constant>
		<constant name="menu_links_groups">Manage groups</constant>
		<constant name="menu_links_manage">Manage links</constant>
		<constant name="menu_links_overview">Sponsored overview</constant>

		<!-- Window Titles -->
		<constant name="title_links_manage">Manage Links</constant>
		<constant name="title_links_overview">Sponsored Links Overview</constant>
		<constant name="title_links_add">Add new link</constant>
		<constant name="title_links_change">Change link</constant>
		<constant name="title_links_delete">Delete link</constant>
		<constant name="title_groups_manage">Manage Groups</constant>
		<constant name="title_groups_create">Create new group</constant>
		<constant name="title_groups_change">Change group name</constant>
		<constant name="title_groups_delete">Delete group</constant>
		<constant name="title_groups_links">Group links</constant>

		<!-- Messages -->
		<constant name="message_link_saved">Link data saved.</constant>
		<constant name="message_link_delete">You are about to remove the following link. Are you sure?</constant>
		<constant name="message_link_deleted">Specified link was removed.</constant>
		<constant name="message_group_links">Selected links are part of the group in question. Links can be members or more than one group.</constant>
		<constant name="message_group_links_updated">Link membership updated.</constant>
		<constant name="message_group_created">New group was created.</constant>
		<constant name="message_group_renamed">Group renamed.</constant>
		<constant name="message_group_delete">You are about to remove the following group. Links contained within a group will *NOT* be removed! Are you sure?</constant>
		<constant name="message_group_deleted">Specified group and link references was removed.</constant>

		<!-- Column Names -->
		<constant name="column_name">Name</constant>
		<constant name="column_text">Text</constant>
		<constant name="column_external">External</constant>
		<constant name="column_sponsored">Sponsored</constant>
		<constant name="column_progress">Progress</constant>
		<constant name="column_clicks">Clicks</constant>
		<constant name="column_total_clicks">Total clicks</constant>

		<!-- Form Labels -->
		<constant name="label_name">Name:</constant>
		<constant name="label_text">Text:</constant>
		<constant name="label_description">Description:</constant>
		<constant name="label_url">URL:</constant>
		<constant name="label_external">Open link in new window/tab</constant>
		<constant name="label_sponsored">Sponsored link</constant>
		<constant name="label_display_limit">Display limit (0 for none):</constant>
		<constant name="label_sponsored_clicks">Sponsored clicks:</constant>
		<constant name="label_total_clicks">Total clicks:</constant>

		<!-- Other -->
		<constant name="links">Links</constant>
		<constant name="add">Add new link</constant>
		<constant name="create_group">Create new group</constant>
		<constant name="groups">Link groups</constant>
		<constant name="overview">Sponsored links</constant>
	</language>
</document>

=== ArseniyK/Caracal/data/system_language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../units/schema/language.dtd">
<document>
	<language name="Srpski" short="sr">
		<constant name="backend_copyright"><![CDATA[Copyright &copy; by <a href="http://way2cu.com">Way2CU</a>. Icons by <a href="http://commons.wikimedia.org/wiki/User:Paintpot">Paintpot</a>. All rights reserved!]]></constant>

		<!-- Column Names -->
		<constant name="column_options">Opcije</constant>

		<!-- Buttons -->
		<constant name="add">Unos</constant>
		<constant name="new">Novo</constant>
		<constant name="change">Izmena</constant>
		<constant name="delete">Brisanje</constant>
		<constant name="save">Snimi</constant>
		<constant name="submit">Pošalji</constant>
		<constant name="send">Pošalji</constant>
		<constant name="upload">Pošalji</constant>
		<constant name="cancel">Otkaži</constant>
		<constant name="open">Otvori</constant>
		<constant name="close">Zatvori</constant>
		<constant name="reset">Resetuj</constant>
		<constant name="filter">Filtriraj</constant>
		<constant name="search">Pronađi</constant>
		<constant name="next">Dalje</constant>
		<constant name="back">Nazad</constant>
		<constant name="print">Štampa</constant>

		<!-- Messages -->
		<constant name="message_server_error">Server je naišao na sledeću grešku prilikom obrade podataka:</constant>
		<constant name="message_license_error">Nije Vam dozvoljena upotreba podataka sa ovog sajta!</constant>

		<!-- Page switch -->
		<constant name="page_first">Prva</constant>
		<constant name="page_previous">Prethodna</constant>
		<constant name="page_next">Sledeća</constant>
		<constant name="page_last">Poslednja</constant>

		<!-- Other language specific data formats -->
		<constant name="format_date">d.m.Y.</constant>
		<constant name="format_date_short">d.m.Y.</constant>
		<constant name="format_time">H:i:s</constant>
		<constant name="format_time_short">H:i:s</constant>
	</language>
	<language name="English" short="en" default="yes">
		<constant name="backend_copyright"><![CDATA[Copyright &copy; by <a href="http://way2cu.com">Way2CU</a>. Icons by <a href="http://commons.wikimedia.org/wiki/User:Paintpot">Paintpot</a>. All rights reserved!]]></constant>

		<!-- Column Names -->
		<constant name="column_options">Options</constant>

		<!-- Buttons -->
		<constant name="add">Add</constant>
		<constant name="new">New</constant>
		<constant name="change">Change</constant>
		<constant name="delete">Delete</constant>
		<constant name="save">Save</constant>
		<constant name="submit">Submit</constant>
		<constant name="send">Send</constant>
		<constant name="upload">Upload</constant>
		<constant name="cancel">Cancel</constant>
		<constant name="open">Open</constant>
		<constant name="close">Close</constant>
		<constant name="reset">Reset</constant>
		<constant name="filter">Filter</constant>
		<constant name="search">Search</constant>
		<constant name="next">Next</constant>
		<constant name="back">Back</constant>
		<constant name="print">Print</constant>

		<!-- Messages -->
		<constant name="message_server_error">Server experienced the following error:</constant>
		<constant name="message_license_error">You are not authorized to use services from this site!</constant>

		<!-- Page switch -->
		<constant name="page_first">First</constant>
		<constant name="page_previous">Previous</constant>
		<constant name="page_next">Next</constant>
		<constant name="page_last">Last</constant>

		<!-- Other language specific data formats -->
		<constant name="format_date">m/d/Y</constant>
		<constant name="format_date_short">m/d/Y</constant>
		<constant name="format_time">H:i:s</constant>
		<constant name="format_time_short">H:i:s</constant>
	</language>
	<language name="Español" short="es" >
		<constant name="backend_copyright"><![CDATA[Copyright &copy; by <a href="http://way2cu.com">Way2CU</a>. Icons by <a href="http://commons.wikimedia.org/wiki/User:Paintpot">Paintpot</a>. All rights reserved!]]></constant>

		<!-- Column Names -->
		<constant name="column_options">Options</constant>

		<!-- Buttons -->
		<constant name="add">Add</constant>
		<constant name="new">New</constant>
		<constant name="change">Change</constant>
		<constant name="delete">Delete</constant>
		<constant name="save">Save</constant>
		<constant name="submit">Submit</constant>
		<constant name="send">Enviar</constant>
		<constant name="upload">Upload</constant>
		<constant name="cancel">Cancel</constant>
		<constant name="open">Open</constant>
		<constant name="close">Close</constant>
		<constant name="reset">Borrar</constant>
		<constant name="filter">Filter</constant>

		<!-- Messages -->
		<constant name="message_server_error">Server experienced the following error:</constant>
		<constant name="message_license_error">You are not authorized to use services from this site!</constant>

		<!-- Page switch -->
		<constant name="page_first">First</constant>
		<constant name="page_previous">Previous</constant>
		<constant name="page_next">Next</constant>
		<constant name="page_last">Last</constant>

		<!-- Other language specific data formats -->
		<constant name="format_date">m/d/Y</constant>
		<constant name="format_date_short">m/d/Y</constant>
		<constant name="format_time">H:i:s</constant>
		<constant name="format_time_short">H:i:s</constant>
	</language>
	<language name="עברית" short="he" rtl="yes">
		<constant name="backend_copyright"><![CDATA[Copyright &copy; by <a href="http://way2cu.com">Way2CU</a>. Icons by <a href="http://commons.wikimedia.org/wiki/User:Paintpot">Paintpot</a>. All rights reserved!"]]></constant>

		<!-- Column Names -->
		<constant name="column_options">אפשרויות</constant>

		<!-- Buttons -->
		<constant name="add">הוסף</constant>
		<constant name="new">חדש</constant>
		<constant name="change">שנה</constant>
		<constant name="delete">מחק</constant>
		<constant name="save">שמור</constant>
		<constant name="submit">עדכן</constant>
		<constant name="send">שלח</constant>
		<constant name="upload">העלה</constant>
		<constant name="cancel">בטל</constant>
		<constant name="open">פתח</constant>
		<constant name="close">סגור</constant>
		<constant name="reset">אפס</constant>
		<constant name="filter">לסנן</constant>
		<constant name="search">לחפש</constant>
		<constant name="next">הבא</constant>
		<constant name="back">הקודם</constant>
		<constant name="print">Print</constant>

		<!-- Messages -->
		<constant name="message_server_error">השרת חווה את הבעיה הבאה:</constant>
		<constant name="message_license_error">אינך מורשה לקבל שירותים מאתר זה</constant>

		<!-- Page switch -->
		<constant name="page_first">ראשון</constant>
		<constant name="page_previous">הקודם</constant>
		<constant name="page_next">הבא</constant>
		<constant name="page_last">אחרון</constant>

		<!-- Other language specific data formats -->
		<constant name="format_date">d.m.Y.</constant>
		<constant name="format_date_short">d.m.Y.</constant>
		<constant name="format_time">H:i:s</constant>
		<constant name="format_time_short">H:i:s</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/search/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="search_results" value="Search Results" />
		<constant name="score" value="Score" />
		<constant name="read_more" value="Read More" />
		<constant name="search" value="Search"/>
		<constant name="message_no_results" value="No results found!"/>
	</language>
	<language short="iw">
		<constant name="search_results" value="תוצאות חיפוש" />
		<constant name="score" value="מספר מופעים בטקסט" />
		<constant name="read_more" value="קרא עוד" />
		<constant name="message_no_results" value="לא נמצאו תוצאות תואמות" />
	</language>
	<language short="sr-lat">
		<constant name="search_results" value="Rezultati Pretrage" />
		<constant name="score" value="Tačnost" />
		<constant name="read_more" value="Više" />
		<constant name="search" value="Traži"/>
		<constant name="message_no_results" value="Nema rezultata za date kriterijume pretrage!"/>
	</language>
</document>

=== ArseniyK/Caracal/modules/code_project/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_codes">Projects</constant>
		<constant name="menu_codes_manage">Manage project codes</constant>
		
		<constant name="title_codes_manage">Manage project codes</constant>
		<constant name="title_codes_add">Add new project code</constant>
		<constant name="title_codes_change">Change project code</constant>
		<constant name="title_codes_delete">Delete project code</constant>
		
		<constant name="column_code">Code</constant>
		
		<constant name="label_code">Code:</constant>
		<constant name="label_url">URL:</constant>
		
		<constant name="message_code_saved">Code data is saved!</constant>
		<constant name="message_code_delete">Are you sure about removing the following code?</constant>
		<constant name="message_code_deleted">Specified code was removed.</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/kabalah/data/language.xml
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language name="English" short="en">
		<constant name="menu_title" value="Kabalah"/>
		<constant name="menu_questions" value="Edit questions" />
		<constant name="menu_answers" value="Edit answers" />

		<constant name="title_questions" value="Kabalah: Questions" />
		<constant name="title_questions_new" value="Create question" />
		<constant name="title_questions_change" value="Change question" />
		<constant name="title_questions_delete" value="Delete question" />
		<constant name="title_fields" value="Kabalah Fields: " />
		<constant name="title_fields_new" value="Create field" />
		<constant name="title_fields_change" value="Change field" />
		<constant name="title_fields_delete" value="Delete field" />
		<constant name="title_answers" value="Kabalah: Answers" />
		<constant name="title_answers_new" value="Create answer" />
		<constant name="title_answers_change" value="Change answer" />
		<constant name="title_answers_delete" value="Delete answer" />

		<constant name="message_question_saved" value="Question data has been saved!"/>
		<constant name="message_question_delete" value="The following question will be removed from the system. Additionaly all answers and fields related to this question will be removed too! Are you sure?"/>
		<constant name="message_question_deleted" value="Question data has been deleted!"/>
		<constant name="message_field_saved" value="Field data has been saved!"/>
		<constant name="message_field_delete" value="The following field will be removed from the system. Are you sure?"/>
		<constant name="message_field_deleted" value="Field data has been deleted!"/>
		<constant name="message_answer_saved" value="Answer data has been saved!"/>
		<constant name="message_answer_delete" value="The following answer will be removed from the system. Are you sure?"/>
		<constant name="message_answer_deleted" value="Answer data has been deleted!"/>

		<constant name="new" value="Create new" />
		<constant name="change" value="Change" />
		<constant name="delete" value="Delete" />
		<constant name="fields" value="Fields" />
		<constant name="save" value="Save" />
		<constant name="reset" value="Reset" />
		<constant name="cancel" value="Cancel" />
		<constant name="close" value="Close" />

		<constant name="label_question_id" value="ID Number:"/>
		<constant name="label_question_title" value="Title:"/>
		<constant name="label_question_short_description" value="Short description:"/>
		<constant name="label_question_description" value="Description:"/>
		<constant name="label_question_formula" value="Formula &lt;small&gt;(eg.: sum($name) + $last_name[1] / 2)&lt;/small&gt;:"/>
		<constant name="label_field_question" value="Question:"/>
		<constant name="label_field_type" value="Type:"/>
		<constant name="label_field_name" value="Name:"/>
		<constant name="label_field_label" value="Label:"/>
		<constant name="label_field_default" value="Default value:"/>
		<constant name="label_field_order" value="Order:"/>
		<constant name="label_answer_number" value="Result number:"/>
		<constant name="label_answer_question" value="Question:"/>
		<constant name="label_answer_title" value="Title:"/>
		<constant name="label_answer_short_description" value="Short description:"/>
		<constant name="label_answer_description" value="Description:"/>

		<constant name="field_type_text" value="Text"/>
		<constant name="field_type_date" value="Date"/>
		<constant name="field_type_number" value="Number"/>

		<constant name="column_question_id" value="ID"/>
		<constant name="column_question_title" value="Title"/>
		<constant name="column_field_name" value="Name"/>
		<constant name="column_field_type" value="Type"/>
		<constant name="column_answer_number" value="Result"/>
		<constant name="column_answer_answer" value="Answer title"/>
		<constant name="column_answer_question" value="Question"/>
		<constant name="column_options" value="Options"/>
	</language>
	<language name="Hebrew" short="heb">
		<constant name="menu_title" value="קבלה" />
		<constant name="menu_questions" value="ערוך שאלות" />
		<constant name="menu_answers" value="ערוך תשובות לשאלה" />

		<constant name="title_questions" value="קבלה : שאלות" />
		<constant name="title_questions_new" value="צור שאלה" />
		<constant name="title_questions_change" value="ערוך שאלה" />
		<constant name="title_questions_delete" value="מחק שאלה" />
		<constant name="title_fields" value="קבלה : שדות" />
		<constant name="title_fields_new" value="Create field" />
		<constant name="title_fields_change" value="Change field" />
		<constant name="title_fields_delete" value="Delete field" />
		<constant name="title_answers" value="קבלה : תשובות" />
		<constant name="title_answers_new" value="צור תשובה" />
		<constant name="title_answers_change" value="ערוך תשובה" />
		<constant name="title_answers_delete" value="מחק תשובה" />

		<constant name="message_question_saved" value="תוכן השאלה נשמר!"/>
		<constant name="message_question_delete" value="The following question will be removed from the system. Additionaly all answers and fields related to this question will be removed too! Are you sure?"/>
		<constant name="message_question_deleted" value="תוכן השאלה הוסר!"/>
		<constant name="message_field_saved" value="Field data has been saved!"/>
		<constant name="message_field_delete" value="The following field will be removed from the system. Are you sure?"/>
		<constant name="message_field_deleted" value="Field data has been deleted!"/>
		<constant name="message_answer_saved" value="תוכן השאלה נשמר בהצלחה!"/>
		<constant name="message_answer_delete" value="השאלה תוסר מהמערכת, האם אתה בטוח?"/>
		<constant name="message_answer_deleted" value="תוכן התשובה נמחק!"/>

		<constant name="new" value="צור" />
		<constant name="change" value="ערוך" />
		<constant name="delete" value="מחק" />
		<constant name="fields" value="Fields" />
		<constant name="save" value="שמור" />
		<constant name="reset" value="אפס" />
		<constant name="cancel" value="בטל" />
		<constant name="close" value="סגור" />

		<constant name="label_question_id" value="מספר זיהוי"/>
		<constant name="label_question_title" value="כותרת:"/>
		<constant name="label_question_short_description" value="תאור קצר:"/>
		<constant name="label_question_description" value="תאור:"/>
		<constant name="label_question_formula" value="Formula &lt;small&gt;(eg.: sum($name) + $last_name[1] / 2)&lt;/small&gt;:"/>
		<constant name="label_field_question" value="Question:"/>
		<constant name="label_field_type" value="Type:"/>
		<constant name="label_field_name" value="Name:"/>
		<constant name="label_field_label" value="Label:"/>
		<constant name="label_field_default" value="Default value:"/>
		<constant name="label_answer_number" value="תוצאת החישוב:"/>
		<constant name="label_answer_question" value="שאלה:"/>
		<constant name="label_answer_title" value="כותרת:"/>
		<constant name="label_answer_short_description" value="תאור קצר:"/>
		<constant name="label_answer_description" value="תאור:"/>

		<constant name="field_type_text" value="Text"/>
		<constant name="field_type_date" value="Date"/>
		<constant name="field_type_number" value="Number"/>

		<constant name="column_question_id" value="מספר"/>
		<constant name="column_question_title" value="כותרת"/>
		<constant name="column_field_name" value="Name"/>
		<constant name="column_field_type" value="Type"/>
		<constant name="column_answer_number" value="תוצאה"/>
		<constant name="column_answer_answer" value="כותרת התשובה"/>
		<constant name="column_answer_question" value="שאלה"/>
		<constant name="column_options" value="אשפרויות"/>
	</language>
</document>

=== ArseniyK/Caracal/modules/feedback/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_feedback">Feedback</constant>
		<constant name="menu_feedback_show">Show feedback</constant>

		<constant name="title_feedback_show">Feedback</constant>
		<constant name="title_feedback_change">Feedback: Change status</constant>
		<constant name="title_feedback_delete">Feedback: Delete</constant>

		<constant name="column_user">User</constant>
		<constant name="column_page">Page</constant>
	</language>

	<language short="he">
		<constant name="menu_feedback">Feedback</constant>
		<constant name="menu_feedback_show">Show feedback</constant>

		<constant name="title_feedback_show">Feedback</constant>
		<constant name="title_feedback_change">Feedback: Change status</constant>
		<constant name="title_feedback_delete">Feedback: Delete</constant>
	</language>

	<language short="sr">
		<constant name="menu_feedback">Feedback</constant>
		<constant name="menu_feedback_show">Show feedback</constant>

		<constant name="title_feedback_show">Feedback</constant>
		<constant name="title_feedback_change">Feedback: Change status</constant>
		<constant name="title_feedback_delete">Feedback: Delete</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/shop/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_shop">Shop</constant>
		<constant name="menu_items">Manage items</constant>
		<constant name="menu_categories">Manage categories</constant>
		<constant name="menu_payment_methods">Payment methods</constant>
		<constant name="menu_purchases">Purchases</constant>
		<constant name="menu_stocks">Stocks</constant>
		<constant name="menu_special_offers">Special offers</constant>
		<constant name="menu_currencies">Currencies</constant>

		<constant name="title_manage_items">Shop: Manage items</constant>
		<constant name="title_manage_categories">Shop: Manage categories</constant>
		<constant name="title_item_add">Shop: Add new item</constant>
		<constant name="title_currencies">Shop: Available currencies</constant>
		
		<constant name="column_name">Name</constant>
		<constant name="column_price">Price</constant>
		<constant name="column_rating">Rating</constant>
		
		<constant name="label_name">Name:</constant>
		<constant name="label_description">Description:</constant>
		<constant name="label_price">Price:</constant>
		<constant name="label_currency">Currency:</constant>

		<constant name="add_item">Add new item</constant>
		<constant name="manage_categories">Manage categories</constant>
	</language>
</document>
