=== ArseniyK/Caracal/units/schema/language.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Language File Specification
	Copyright (c) 2010. by RCF Group
	
	Author: MeanEYE.rcf
-->
<!ELEMENT document (language*)>

<!ELEMENT language (constant*)>
<!ATTLIST language name CDATA #IMPLIED>
<!ATTLIST language short CDATA #REQUIRED>
<!ATTLIST language default (yes|no) "no">
<!ATTLIST language rtl (yes|no) "no">

<!ELEMENT constant ANY>
<!ATTLIST constant name CDATA #REQUIRED>
<!ATTLIST constant value CDATA #IMPLIED>

=== ArseniyK/Caracal/modules/leads/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_leads">Leads</constant>
		<constant name="menu_results">Show leads</constant>
		<constant name="menu_types">Manage types</constant>
		<constant name="menu_export">Export</constant>

		<constant name="title_results">Leads: Results</constant>
		<constant name="title_types">Leads: Types</constant>
		<constant name="title_types_new">Leads: New type</constant>
		<constant name="title_types_change">Leads: Change type</constant>
		<constant name="title_types_delete">Leads: Delete type</constant>

		<constant name="message_types_saved">Leads type was saved!</constant>
		<constant name="message_types_delete">You are about to remove the following type and all of it's entries. Are you sure?</constant>
		<constant name="message_types_deleted">Specified type and its entries were removed!</constant>

		<constant name="column_name">Name</constant>

		<constant name="label_name">Name:</constant>
		<constant name="label_fields">Fields:</constant>
		<constant name="label_unique_address">Allow only one entry per IP address</constant>
		<constant name="label_send_email">Send email to default recipient on submit</constant>
	</language>
	<language short="he">
		<constant name="menu_leads">Leads</constant>
		<constant name="menu_results">Show leads</constant>
		<constant name="menu_types">Manage types</constant>
		<constant name="menu_export">Export</constant>

		<constant name="title_results">Leads: Results</constant>
		<constant name="title_types">Leads: Types</constant>
		<constant name="title_types_new">Leads: New type</constant>
		<constant name="title_types_change">Leads: Change type</constant>
		<constant name="title_types_delete">Leads: Delete type</constant>

		<constant name="message_types_saved">Leads type was saved!</constant>
		<constant name="message_types_delete">You are about to remove the following type and all of it's entries. Are you sure?</constant>
		<constant name="message_types_deleted">Specified type and its entries were removed!</constant>

		<constant name="column_name">Name</constant>

		<constant name="label_name">Name:</constant>
		<constant name="label_fields">Fields:</constant>
		<constant name="label_unique_address">Allow only one entry per IP address</constant>
		<constant name="label_send_email">Send email to default recipient on submit</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/country_list/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en" rtl="no">
		<constant name="country_field_name">Country list</constant>
		<constant name="state_field_name">State list</constant>
	</language>

	<language short="he" rtl="no">
		<constant name="country_field_name">Country list</constant>
		<constant name="state_field_name">State list</constant>
	</language>

	<language short="ar" rtl="no">
		<constant name="country_field_name">Country list</constant>
		<constant name="state_field_name">State list</constant>
	</language>

	<language short="sr" rtl="no">
		<constant name="country_field_name">Country list</constant>
		<constant name="state_field_name">State list</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/paypal/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_paypal">PayPal</constant>
		<constant name="menu_subscriptions">Subscriptions</constant>
		<constant name="menu_bridges">Bridges</constant>
		<constant name="menu_items">Items</constant>
		<constant name="menu_transactions">Transactions</constant>

		<constant name="title_transactions">Transactions</constant>

		<constant name="column_payer">Payer</constant>
		<constant name="column_date">Date</constant>
		<constant name="column_gross">Gross</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/affiliates/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_affiliates">Affiliates</constant>
		<constant name="menu_manage_affiliates">Manage affiliates</constant>
		<constant name="menu_referral_urls">Referral URLs</constant>
		<constant name="menu_information">Affiliate information</constant>

		<constant name="title_referrals">Affiliate Referrals</constant>
		<constant name="title_affiliates">Manage Affiliates</constant>
		<constant name="title_affiliates_add">Affiliates: Add new</constant>
		<constant name="title_affiliates_change">Affiliates: Change data</constant>
		<constant name="title_affiliates_delete">Affiliates: Delete affiliate</constant>
		<constant name="title_affiliate_information">Affiliate Information</constant>

		<constant name="message_affiliate_saved">Affiliate data was saved!</constant>
		<constant name="message_affiliate_not_unique">New affiliate was not saved because specified ID is not unique!</constant>
		<constant name="message_affiliate_delete">You are about to remove the following affiliate and accumulated data with it. Are you sure?</constant>
		<constant name="message_affiliate_deleted">Affiliate and its referrals were deleted.</constant>

		<constant name="new_affiliate">New affiliate</constant>
		<constant name="group_by">Group by:</constant>
		<constant name="affiliate">Affiliate:</constant>

		<constant name="column_name">Name</constant>
		<constant name="column_referrals">Referrals</constant>
		<constant name="column_clicks">Clicks</constant>
		<constant name="column_conversions">Conversions</constant>
		<constant name="column_rate">Rate</constant>
		<constant name="column_affiliate">Affiliate</constant>
		<constant name="column_url">Referral URL</constant>
		<constant name="column_landing">Landing page</constant>

		<constant name="label_name">Name:</constant>
		<constant name="label_uid">Unique ID:</constant>
		<constant name="label_user">System user:</constant>
		<constant name="label_active">Affiliate account is active</constant>
		<constant name="label_clicks">Clicks:</constant>
		<constant name="label_conversions">Conversions:</constant>
		<constant name="label_rate">Rate:</constant>
		<constant name="label_url">Page URL:</constant>
		<constant name="label_url_output">URL with affiliate ID:</constant>

		<constant name="tab_general">Information</constant>
		<constant name="tab_generate">Generate URL</constant>

		<constant name="option_url">Referral URL</constant>
		<constant name="option_landing">Landing page</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/survey/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_survey">Survey</constant>
		<constant name="menu_results">Results of survey</constant>
		<constant name="menu_types">Survey types</constant>

		<constant name="title_results">Survey: Results</constant>
		<constant name="title_types">Survey: Types</constant>
		<constant name="title_types_new">Survey: New type</constant>
		<constant name="title_types_change">Survey: Change type</constant>
		<constant name="title_types_delete">Survey: Delete type</constant>

		<constant name="column_name">Name</constant>

		<constant name="label_name">Name:</constant>
		<constant name="label_fields">Fields:</constant>
	</language>
	<language short="iw">
		<constant name="menu_survey">Survey</constant>
		<constant name="menu_results">Results of survey</constant>
		<constant name="menu_types">Survey types</constant>

		<constant name="title_results">Survey: Results</constant>
		<constant name="title_types">Survey: Types</constant>
		<constant name="title_types_new">Survey: New type</constant>
		<constant name="title_types_change">Survey: Change type</constant>
		<constant name="title_types_delete">Survey: Delete type</constant>

		<constant name="column_name">Name</constant>

		<constant name="label_name">Name:</constant>
		<constant name="label_fields">Fields:</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/ctm/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_ctm">CTM</constant>
		<constant name="menu_settings">Settings</constant>

		<constant name="title_settings">CallTrackingMetrics: Settings</constant>

		<constant name="message_saved">Account settings were saved.</constant>

		<constant name="label_account_key">Account key:</constant>
		<constant name="label_account_secret">Account secret:</constant>
	</language>

	<language short="he">
		<constant name="menu_ctm">CTM</constant>
		<constant name="menu_settings">Settings</constant>

		<constant name="title_settings">CallTrackingMetrics: Settings</constant>

		<constant name="message_saved">Account settings were saved.</constant>

		<constant name="label_account_key">Account key:</constant>
		<constant name="label_account_secret">Account secret:</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/tips/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_tips">Tips</constant>
		<constant name="menu_tips_manage">Edit tips</constant>

		<constant name="title_tips_manage">Tips</constant>
		<constant name="title_tips_new">Tips: Create new</constant>
		<constant name="title_tips_change">Tips: Change tip data</constant>
		<constant name="title_tips_delete">Tips: Delete tip</constant>

		<constant name="message_tip_saved">Tip data was saved.</constant>
		<constant name="message_tip_delete">You are about to remove the following tip. Are you sure?</constant>
		<constant name="message_tip_deleted">Specified tip was removed from the system.</constant>

		<constant name="column_tip">Tip</constant>

		<constant name="label_content">Content:</constant>
		<constant name="label_visible">This tip is visible</constant>
	</language>
	<language short="he">
		<constant name="menu_tips">טיפים</constant>
		<constant name="menu_tips_manage">ערוך טיפים</constant>

		<constant name="title_tips_manage">טיפים</constant>
		<constant name="title_tips_new">טיפים : צור חדש</constant>
		<constant name="title_tips_change">טיפים : שנה תוכן הטיפ</constant>
		<constant name="title_tips_delete">טיפים : מחק טיפ</constant>

		<constant name="message_tip_saved">תוכן הטיפ נשמר</constant>
		<constant name="message_tip_delete">אתה עומד למחוק את הטיפ, אתה בטוח?</constant>
		<constant name="message_tip_deleted">הטיפ הוסר מהמערכת.</constant>

		<constant name="column_tip">טיפ</constant>

		<constant name="label_content">תוכן:</constant>
		<constant name="label_visible">הטיפ מוצג</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/faq/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_faq">FAQ</constant>
		<constant name="menu_manage_questions">Manage questions</constant>

		<constant name="title_questions">FAQ</constant>
		<constant name="title_question_new">FAQ: New question</constant>
		<constant name="title_question_change">FAQ: Change question</constant>
		<constant name="title_question_delete">FAQ: Delete question</constant>

		<constant name="message_question_delete">You are about to remove the following question. Are you sure?</constant>
		<constant name="message_question_deleted">Question was deleted!</constant>
		<constant name="message_question_saved">Question data was saved!</constant>

		<constant name="new_question">New question</constant>

		<constant name="column_question">Question</constant>

		<constant name="label_question">Question:</constant>
		<constant name="label_answer">Answer:</constant>
		<constant name="label_visible">Question is visible</constant>
	</language>
</document>
