=== ArseniyK/Caracal/units/schema/language.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Language File Specification
	Copyright (c) 2010. by RCF Group
	
	Author: MeanEYE.rcf
-->
<!ELEMENT document (language*)>

<!ELEMENT language (constant*)>
<!ATTLIST language name CDATA #IMPLIED>
<!ATTLIST language short CDATA #REQUIRED>
<!ATTLIST language default (yes|no) "no">
<!ATTLIST language rtl (yes|no) "no">

<!ELEMENT constant ANY>
<!ATTLIST constant name CDATA #REQUIRED>
<!ATTLIST constant value CDATA #IMPLIED>

=== ArseniyK/Caracal/modules/tranzila/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_tranzila">Tranzila</constant>

		<constant name="title_settings">Tranzila Settings</constant>
		<constant name="payment_method_title">Tranzila</constant>

		<constant name="label_terminal">Terminal name:</constant>
		<constant name="label_url_confirm">Confirmation URL:</constant>
		<constant name="label_url_cancel">Cancel URL:</constant>

		<constant name="message_settings_saved">New settings were saved.</constant>
	</language>
	<language short="iw">
		<constant name="menu_tranzila">טרנזילה</constant>

		<constant name="title_settings">הגדרות טרנזילה</constant>
		<constant name="payment_method_title">טרנזילה</constant>

		<constant name="label_terminal">שם מסוף:</constant>
		<constant name="label_url_confirm">כתובת אישור:</constant>
		<constant name="label_url_cancel">כתובת ביטול:</constant>

		<constant name="message_settings_saved">ההגדרות החדשות נשמרו</constant>
	</language>
</document>

=== ArseniyK/Caracal/modules/chat/data/language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "../../../units/schema/language.dtd">
<document>
	<language short="en">
		<constant name="menu_chat">Chat</constant>
		<constant name="menu_join_chat">Join chat</constant>
		<constant name="menu_settings">Settings</constant>

		<constant name="title_chat">Chat</constant>
		<constant name="title_chat_settings">Chat: Settings</constant>
		<constant name="title_channel_add">Chat: Add Channel</constant>

		<constant name="column_channel">Channel</constant>
		<constant name="column_users">Users</constant>

		<constant name="label_channel">Channel:</constant>
		<constant name="label_chat_log">Chat log:</constant>
		<constant name="label_online_users">Users online:</constant>
		<constant name="label_message">Message:</constant>

		<constant name="add_channel">Add channel</constant>
	</language>
</document>
